### DISCUSSION TITLE
[packer+ansible] docker-compose로 만든 서비스가 EC2 instance에서 확인이 안 되는 이유

### DISCUSSION THREAD

**Discussion by goldrako** [tedilabs/fastcampus-devops#58] [Q&A] [answered]
안녕하세요.
좋은 강의로 큰 도움을 받고 있습니다.

응용실습 중에 문제가 생겼습니다.

`2-ansible/lab/packer-templates/openvpn/ansible/playbook.yaml` 을 참조하여 다음과 같이 
docker-compose를 이용한 jenkins 등 몇가지 서비스를 생성하는 `playbook.yaml`을 만들었습니다.

사전에 `docker-compose.yml`은 목적 디렉토리에 copy 하여 두었습니다.

문제는 **debug** 상으로는 ssh 접속해서 보면
```sh
$ docker network ls
$ docker ps
```
명령어로 jenkins-net과 jenkins가 정상적이었고 브라우저에서도 확인되었습니다.
최종 빌드를 통해 AMI를 생성했습니다.

그런데 AMI를 통해 EC2 instance를 생성해서 ssh로 접속 확인해 보면
jenkins network도 서비스도 전혀 올라오지 않습니다. ( ansible playbook 내의 모듈과 쉘 방식 모두 안 올라옴 )
놓친게 무엇일까요? ( 참고로 ansible 방식을 뺀 packer shell 방식은 잘 됨 ) 

> ※ triggers를 통해 `provisioner "remote-exec"` ansible-playbook을 재실행하는 것은 Terraform으로 바로 만드는 것과 차이가 없는 것 같습니다.

```yml
  - name: Install docker Python Package
    pip:
      name: 
        - docker
        - docker-compose
      state: present

  # docker command 로 network 생성( jenkins, ... ) : shell로 docker-compose 테스트 용도
  # - name: Install docker-compose from official github repo
  #   # remote_user: ansible_ubuntu_demo
  #   get_url:
  #     url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
  #     dest: /usr/local/bin/docker-compose
  #     # mode: 'u+x,g+x'
  #     mode: '0755'
  - name: "Create a docker network"
    docker_network:
      name: "{{ item }}"
      state: present
    loop:
      - jenkins-net
      - ...

  # - name: "Create a docker network"
  #   shell: "docker network create --driver bridge {{ item }}"
  #   loop:
  #     - jenkins-net
  #     - ...

# jenkins --- 실행 후 패스워드 확인 : docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword
  - name: deploy Jenkins Docker Compose stack
    docker_compose:
      project_src: /data/jenkins
      files:
      - docker-compose.yml
      state: present
    # shell: |
    #   cd /data/jenkins
    #   docker network create --driver bridge jenkins-net
    #   docker-compose up -d
```
